name: Run Classview Every Hour

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  classview:
    name: Runner ${{ matrix.runner }}
    runs-on: ubuntu-latest
    timeout-minutes: 300   # 5 hours 30 minutes

    strategy:
      matrix:
        runner: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Pull classview image
        run: docker pull jeanrata/classview

      - name: Run classview container
        run: |
          docker run \
            --cap-add=NET_ADMIN \
            --device /dev/net/tun \
            --name classview-${{ matrix.runner }} \
            jeanrata/classview
